version: '3.9'
services:
  redis-db:
    image: redis:7.2-alpine
    ports:
      - '16379:6379'

  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: abank

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_DSN: postgresql://postgres:123123123@postgres-db:5432/abank?sslmode=disable
      REDIS_URI: redis://redis-db:6379
      APP_ENV: dev
    ports:
      - '4000:4000'
