version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  abank:
    cmds:
      - go run main.go

  migrate:
    desc: migrate db
    cmds:
      - go run main.go migrate {{.CLI_ARGS}}
